/*
 * rcpdefs.h
 *
 *  Created on: Aug 15, 2012
 *      Author: arash
 *
 *  This file is part of rcpplus
 *
 *  rcpplus is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  rcpplus is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with rcpplus.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _RCP_DEFS_H_
#define _RCP_DEFS_H_

#define RCP_VERSION					3

#define RCP_CONTROL_PORT			1756

#define TPKT_VERSION				3
#define TPKT_HEADER_LENGTH			4

#define RCP_HEADER_LENGTH			16

#define RCP_MAX_PACKET_LEN			1500

#define RCP_MD5_RANDOM_LEN			16

#define RCP_DATA_TYPE_F_FLAG		0x00 // (1 Byte)
#define RCP_DATA_TYPE_T_OCTET		0x01 // (1 Byte)
#define RCP_DATA_TYPE_T_WORD		0x02 // (2 Byte)
#define RCP_DATA_TYPE_T_INT			0x04 // (4 Byte)
#define RCP_DATA_TYPE_T_DWORD		0x08 // (4 Byte)
#define RCP_DATA_TYPE_P_OCTET		0x0C // (N Byte)
#define RCP_DATA_TYPE_P_STRING		0x10 // (N Byte)
#define RCP_DATA_TYPE_P_UNICODE		0x14 // (N Byte)

#define RCP_MEDIA_TYPE_VIDEO		0x01
#define RCP_MEDIA_TYPE_AUDIO		0x02
#define RCP_MEDIA_TYPE_DATA			0x03

#define RCP_CONNECTION_METHOD_GET			0x00
#define RCP_CONNECTION_METHOD_PUT			0x01
#define RCP_CONNECTION_METHOD_KEYTRANSPORT	0xE0

#define RCP_VIDEO_CODING_MPEG4		0x0004 // elementary stream
#define RCP_VIDEO_CODING_MPEG2V		0x0008 // only video
#define RCP_VIDEO_CODING_METADATA	0x0010 // output from motion detection
#define RCP_VIDEO_CODING_H264		0x0040
#define RCP_VIDEO_CODING_JPEG		0x0080
#define RCP_VIDEO_CODING_RECORDED	0x4000
#define RCP_VIDEO_CODING_MPEG2S		0x8000 // program stream

#define RCP_VIDEO_RESOLUTION_QCIF		0x0001
#define RCP_VIDEO_RESOLUTION_CIF		0x0002
#define RCP_VIDEO_RESOLUTION_2CIF		0x0004
#define RCP_VIDEO_RESOLUTION_4CIF		0x0008
#define RCP_VIDEO_RESOLUTION_QVGA		0x0200
#define RCP_VIDEO_RESOLUTION_VGA		0x0400
#define RCP_VIDEO_RESOLUTION_HD720		0x0800
#define RCP_VIDEO_RESOLUTION_HD_1080	0x1000

#define RCP_MEP_UDP					0x01
#define RCP_MEP_TCP					0x04

#define RCP_COMMAND_MODE_READ		0x00
#define RCP_COMMAND_MODE_WRITE		0x01

#define RCP_PACKET_ACTION_REQUEST	0x00
#define RCP_PACKET_ACTION_REPLY		0x01
#define RCP_PACKET_ACTION_MESSAGE	0x02
#define RCP_PACKET_ACTION_ERROR		0x03

#define RCP_USER_LEVEL_USER			0x01 // for video access and control over the video stream (e.g. caminput)
#define RCP_USER_LEVEL_SERVICE		0x02 // for video and all administrative access
#define RCP_USER_LEVEL_LIVE			0x03 // for video access only; no control

#define RCP_REGISTRATION_TYPE_NORMAL	0x01
#define RCP_REGISTRATION_TYPE_HOOKON	0x02
#define RCP_REGISTRATION_TYPE_HOOKBACK	0x03

#define RCP_ENCRYPTION_MODE_PLAIN		0x00
#define RCP_ENCRYPTION_MODE_MD5			0x01

#define RCP_CODER_DECODER				0x00
#define RCP_CODER_ENCODER				0x01

#define RCP_ERROR_UNKNOWN				0xFF
#define RCP_ERROR_INVALID_VERSION		0x10
#define RCP_ERROR_NOT_REGISTERED		0x20
#define RCP_ERROR_INVALID_CLIENT_ID		0x21
#define RCP_ERROR_INVALID_METHOD		0x30
#define RCP_ERROR_INVALID_CMD			0x40
#define RCP_ERROR_INVALID_ACCESS_TYPE	0x50
#define RCP_ERROR_INVALID_DATA_TYPE		0x60
#define RCP_ERROR_WRITE_ERROR			0x70
#define RCP_ERROR_PACKET_SIZE			0x80
#define RCP_ERROR_READ_NOT_SUPPORTED	0x90
#define RCP_ERROR_INVALID_AUTH_LEVEL	0xa0
#define RCP_ERROR_INVAILD_SESSION_ID	0xb0
#define RCP_ERROR_TRY_LATER				0xc0
#define RCP_ERROR_COMMAND_SPECIFIC		0xe0

#define RCP_DEVICE_NCID_NVR				0x1
#define RCP_DEVICE_NCID_VJ8000			0x2
#define RCP_DEVICE_NCID_VIP10			0x3
#define RCP_DEVICE_NCID_VIP1000			0x4
#define RCP_DEVICE_NCID_VJ400			0x6
#define RCP_DEVICE_NCID_VIP100			0x7
#define RCP_DEVICE_NCID_VJEX			0x8
#define RCP_DEVICE_NCID_VJ1000			0x9
#define RCP_DEVICE_NCID_VJ100			0xA
#define RCP_DEVICE_NCID_VJ10			0xB
#define RCP_DEVICE_NCID_VJ8008			0xC
#define RCP_DEVICE_NCID_VJ8004			0xD // (latest unit carrying the old numbering scheme)
#define RCP_DEVICE_ESCAPECODE			0xF // (used to switch over to new detection)

#define RCP_HARDWARE_TYPE_VIN			0x0
#define RCP_HARDWARE_TYPE_VOUT			0x1
#define RCP_HARDWARE_TYPE_VIN_OUT		0x2

#define RCP_HARDWARE_ID_VIPX1					0x01
#define RCP_HARDWARE_ID_VIPX2					0x02
#define RCP_HARDWARE_ID_VIPXDEC					0x03
#define RCP_HARDWARE_ID_VJ_X10					0x05
#define RCP_HARDWARE_ID_VJ_X20					0x06
#define RCP_HARDWARE_ID_VJ_X40					0x07
#define RCP_HARDWARE_ID_VJ_X40_ECO				0x08
#define RCP_HARDWARE_ID_VJ_X10_ECO				0x09
#define RCP_HARDWARE_ID_VJ_X20_ECO				0x0A
#define RCP_HARDWARE_ID_IP_PANEL				0x0d
#define RCP_HARDWARE_ID_GEN4					0x0e
#define RCP_HARDWARE_ID_M1600					0x0f
#define RCP_HARDWARE_ID_FLEXIDOME				0x11
#define RCP_HARDWARE_ID_M1600_DEC				0x13
#define RCP_HARDWARE_ID_M1600_XFM				0x15
#define RCP_HARDWARE_ID_AUTODOME				0x16
#define RCP_HARDWARE_ID_NBC_225P				0x1a
#define RCP_HARDWARE_ID_VIPX1_XF				0x1e
#define RCP_HARDWARE_ID_NBC_225W				0x1f
#define RCP_HARDWARE_ID_NBC_255P				0x20
#define RCP_HARDWARE_ID_NBC_255W				0x21
#define RCP_HARDWARE_ID_AUTODOME_EASY_II		0x23
#define RCP_HARDWARE_ID_AUTODOME_EASY_II_E		0x24
#define RCP_HARDWARE_ID_VIPX1_XF_E				0x25
#define RCP_HARDWARE_ID_VIPX1_XF_W				0x28
#define RCP_HARDWARE_ID_VG5_AUTODOME_700		0x29
#define RCP_HARDWARE_ID_NDC_455_P				0x2a
#define RCP_HARDWARE_ID_NDC_455_P_IVA			0x2b
#define RCP_HARDWARE_ID_NBC_455_P				0x2c
#define RCP_HARDWARE_ID_NBC_455_P_IVA			0x2d
#define RCP_HARDWARE_ID_VG4_AUTODOME			0x2e
#define RCP_HARDWARE_ID_NDC_225_P				0x2f
#define RCP_HARDWARE_ID_NDC_255_P				0x30
#define RCP_HARDWARE_ID_VOT						0x32
#define RCP_HARDWARE_ID_DINION_720P				0x39
#define RCP_HARDWARE_ID_FLEXIDOME_720P			0x3b
#define RCP_HARDWARE_ID_NDC_265_W				0x3c
#define RCP_HARDWARE_ID_NDC_265_P				0x3d
#define RCP_HARDWARE_ID_NBC_265_P				0x3e
#define RCP_HARDWARE_ID_NDC_225_PI				0x3f
#define RCP_HARDWARE_ID_NTC_255_PI				0x40
#define RCP_HARDWARE_ID_JR_DOME_HD				0x41
#define RCP_HARDWARE_ID_JR_DOME_HD_FIXED		0x42
#define RCP_HARDWARE_ID_EX30_IR					0x43
#define RCP_HARDWARE_ID_GEN5_HD					0x45
#define RCP_HARDWARE_ID_EX65					0x46
#define RCP_HARDWARE_ID_VRM						0xfc
#define RCP_HARDWARE_ID_VIDOS_SERVER			0xfd
#define RCP_HARDWARE_ID_VIDOS_MONITOR			0xfe

#define RCP_COMMAND_CONF_RCP_CLIENT_REGISTRATION		0xff00
#define RCP_COMMAND_CONF_RCP_CLIENT_UNREGISTER			0xff01
#define RCP_COMMAND_CONF_RCP_CLIENT_TIMEOUT_WARNING		0xff03
#define RCP_COMMAND_CONF_RCP_REG_MD5_RANDOM				0xff05
#define RCP_COMMAND_CONF_RCP_TRANSFER_TRANSPARENT_DATA	0xffdd
#define RCP_COMMAND_CONF_CONNECT_PRIMITIVE				0xff0c
#define RCP_COMMAND_CONF_DISCONNECT_PRIMITIVE			0xff0d
#define RCP_COMMAND_CONF_CONNECT_TO						0xffcc
#define RCP_COMMAND_CONF_ACTIVE_CONNECTION_LIST			0xffc1
#define RCP_COMMAND_CONF_MEDIA_SOCKETS_COMPLETE			0xffc7
#define RCP_COMMAND_CONF_RCP_CONNECTIONS_ALIVE			0xffc2
#define RCP_COMMAND_CONF_CAPABILITY_LIST				0xff10
#define RCP_COMMAND_CONF_RCP_CODER_LIST					0xff11
#define RCP_COMMAND_CONF_PUBLISH_MEDIA_KEYS				0x09fc
#define RCP_COMMAND_CONF_CRYPT_KEYAUDIO_ENC				0x09fe
#define RCP_COMMAND_CONF_CRYPT_KEYVIDEO_ENC				0x09ed
#define RCP_COMMAND_CONF_CRYPT_KEYAUDIO_DEC				0x09ff
#define RCP_COMMAND_CONF_CRYPT_KEYVIDEO_DEC				0x0a00
#define RCP_COMMAND_CONF_CRYPT_KEY_GENERATE_ALL			0x0a13
#define RCP_COMMAND_CONF_UNIT_NAME						0x0024
#define RCP_COMMAND_CONF_UNIT_ID						0x0025
#define RCP_COMMAND_CONF_CAMNAME						0x0019
#define RCP_COMMAND_CONF_CAMNAME2						0x0a7e
#define RCP_COMMAND_CONF_HARDWARE_VERSION				0x002e
#define RCP_COMMAND_CONF_SOFTWARE_VERSION				0x002f
#define RCP_COMMAND_CONF_BOOTLOADER_VERSION				0x09ef
#define RCP_COMMAND_CONF_SERIAL_NUMBER					0x0ae7
#define RCP_COMMAND_CONF_CTN							0x0aea
#define RCP_COMMAND_CONF_DEVICE_TYPE_IDS				0x0b07
#define RCP_COMMAND_CONF_SUPPORTED_UPLOAD_TARGETS		0x0b19
#define RCP_COMMAND_CONF_STARTPAGE_BACKGROUND_URL		0x028d
#define RCP_COMMAND_CONF_STARTPAGE_LOGO_URL				0x028e
#define RCP_COMMAND_CONF_STARTPAGE_PRESENTATION_SWITCHES	0x028f
#define RCP_COMMAND_CONF_DYNAMIC_HTML_NAME					0x0298
#define RCP_COMMAND_CONF_DYNAMIC_HTML_DATA					0x0299
#define RCP_COMMAND_CONF_BROWSER_LANGUAGE_VAL				0x01e3
#define RCP_COMMAND_CONF_BROWSER_DATETIME_FORMAT_VAL		0x01e9
#define RCP_COMMAND_CONF_DATE_WDAY							0x0027
#define RCP_COMMAND_CONF_DATE_DAY							0x0028
#define RCP_COMMAND_CONF_DATE_MONTH							0x0029
#define RCP_COMMAND_CONF_DATE_YEAR							0x002a
#define RCP_COMMAND_CONF_TIME_HRS							0x002d
#define RCP_COMMAND_CONF_TIME_MIN							0x002c
#define RCP_COMMAND_CONF_TIME_SEC							0x002b
#define RCP_COMMAND_CONF_TIMEZONE							0x024e
#define RCP_COMMAND_CONF_UTC_ZONEOFFSET						0x031f
#define RCP_COMMAND_CONF_NTP_SERVER_IP_STR					0x024f
#define RCP_COMMAND_CONF_DAY_LIGHT_SAVE_TIME_TABLE			0x0987
#define RCP_COMMAND_CONF_DAY_LIGHT_SAVE_TIME				0x0988
#define RCP_COMMAND_CONF_FORCE_TIME_SET						0x0a0f
#define RCP_COMMAND_CONF_PASSWORD_SETTINGS					0x028b
#define RCP_COMMAND_CONF_REMOTE_PASSWORD					0x010c
#define RCP_COMMAND_CONF_MASTERPWD_CHALLENGE				0x013f
#define RCP_COMMAND_CONF_NBR_OF_TEMP_SENS					0x09c4
#define RCP_COMMAND_CONF_TEMP_SENS							0x09c5
#define RCP_COMMAND_CONF_REDUNDANT_POWER					0x09d7
#define RCP_COMMAND_CONF_POWER_SUPPLY						0x09dd
#define RCP_COMMAND_CONF_NBR_OF_FANS						0x09d5
#define RCP_COMMAND_CONF_FAN_SPEED							0x09d6
#define RCP_COMMAND_CONF_MINIMUM_FAN_SPEED					0x09de
#define RCP_COMMAND_CONF_BOOT_STATE							0x09e3

#endif /* _RCP_DEFS_H_ */
